# ========
#   Hyprland config file for my "linux retroism" rice. Hyprland is the right tool for the job due to all of its available
#   window effects, but you could achieve 99% of the same design with swayfx as well; I just chose hyprland due to
#   compatability issues with nvidia GPU.
# ========


#                                    !!MONITORS!!                                   #
# --------------------------------------------------------------------------------- #
source = ~/.config/hypr/conf/monitors.conf

#                                    !!AUTOSTART!!                                  #
# --------------------------------------------------------------------------------- #
source = ~/.config/hypr/conf/autostart.conf

#                                    !!INPUT!!                                      #
# --------------------------------------------------------------------------------- #
source = ~/.config/hypr/conf/inputs.conf


#                                    !!DESIGN!!                                     #
# --------------------------------------------------------------------------------- #
source = ~/.config/hypr/conf/design.conf

#                                    !!KEYBINDS!!                                   #
# --------------------------------------------------------------------------------- #
source = ~/.config/hypr/conf/keybinds.conf


#                                    !!WINDOW RULES!!                               #
# --------------------------------------------------------------------------------- #
#                                    !!WINDOW RULES!!                               #


# These window rules are fixes to bugs that certain programs I use have, add more as
# you see fit.
