# Simply edit the file path to the wallpaper,
# and set the monitor output to match your setup.
# Use `hyprctl monitors` to get the correct data.

preload = /home/manju/Pictures/Wallpapers/copyleft.png

wallpaper = eDP-1,/home/manju/Pictures/Wallpapers/copyleft.png
