# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.
wallpaper {
    monitor = eDP-1
    #path = /home/anon/Pictures/Wallpapers/lain.png
    #path = /home/anon/Pictures/Wallpapers/aditi.png
    #path = /home/anon/Pictures/Wallpapers/copyleft.png
    path = /home/anon/Pictures/Wallpapers/colorshift.png
}

wallpaper {
    monitor = HDMI-A-1
    #path = /home/anon/Pictures/Wallpapers/lain.png
    #path = /home/anon/Pictures/Wallpapers/aditi.png
    #path = /home/anon/Pictures/Wallpapers/copyleft.png
    #path = /home/anon/Pictures/Wallpapers/colorshift.png
}
splash = false
