# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.
wallpaper {
    monitor = eDP-1
    # replace user placeholder with actual user name 
    path = /home/user/Pictures/Wallpapers/colorshift.png
}
