# ========
#   Hyprland config file for my "diinki aero" rice. Hyprland is the right tool for the job due to all of its available
#   window effects, but you could achieve 99% of the same design with swayfx as well; I just chose hyprland due to
#   compatability issues with nvidia GPU.
# ========


source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/design.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/windowrules.conf