--                                    !!WINDOW RULES!!                               --
-- ----------------------------------------------------------------------------------- --
--                                    !!WINDOW RULES!!                               --
-- These window rules are fixes to bugs that certain programs I use have, add more as
-- you see fit.
--
-- NOTE on min_size: the wiki's confirmed hl.window_rule() examples show two-part
-- geometry effects (like `move`) taking a lua table of two values, e.g.
-- move = {100, 100}. min_size isn't shown explicitly in the pages I could check, so
-- I've mirrored that same {w, h} table shape here. If `hyprctl reload` complains about
-- it, check the min_size entry in the autogenerated stubs at
-- /usr/share/hypr/stubs/hl.meta.lua and swap to whatever shape it expects.


local floating_widgets = { "calcurse", "nmtui", "pulsemixer", "bluetuith", "btop" }
for _, cls in ipairs(floating_widgets) do
    hl.window_rule({
        name = "float-" .. cls,
        match = { class = "^(" .. cls .. ")$" },
        float = true,
        size = { 1080, 720 },
        move = { "(monitor_w-window_w)/2", "(monitor_h-window_h)/2" },
    })
end

-- Fix dragging issues with XWayland
hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Force Sekiro to launch in fullscreen automatically
-- Watch for late window titles and force fullscreen when Sekiro loads
hl.on("window.title", function(w)
    if w ~= nil and (w.title == "Sekiro" or w.class == "sekiro.exe") then
        hl.dispatch(hl.dsp.window.fullscreen({ mode = "fullscreen", action = "set" }))
    end
end)
