# Polkit agents & auth
# You can use whichever one you prefer, but the command would vary.
exec-once = systemctl --user start hyprpolkitagent

# Startup programs, these are mine, most likely you'll have these as well.
exec-once = nm-applet
exec-once = blueman-applet
exec-once = hyprpaper
exec-once = quickshell
exec-once = hyprctl setcursor Hackneyed 24

# Environment variables
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Hackneyed