# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MONITORS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Make sure to customize monitors! This is just my setup so you get an idea.
# run `hyprctl monitors all` to see all your monitors!!!
monitor=eDP-1, 1366x768@60.00, 0x0, 1
# monitor=DP-4, 2560x1440@164.84, 1920x0, 1