#                                    !!WINDOW RULES!!                               #
# --------------------------------------------------------------------------------- #
#                                    !!WINDOW RULES!!                               #
# These window rules are fixes to bugs that certain programs I use have, add more as
# you see fit.
# adding more here as needed.
windowrule = min_size 250 250, match:class ^(Unity)$, match:title ^(Project Settings)$
windowrule = min_size 250 250, move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(Preferences)$
windowrule = min_size 250 250, move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(UnityEditor.AddComponent.AddComponentWindow)$
windowrule = min_size 250 250, match:class ^(Unity)$, match:title ^(Package Manager)$
windowrule = min_size 250 250, match:class ^(Unity)$, match:title ^(UI Toolkit Debugger)$
windowrule = min_size 250 500, match:class ^(Unity)$, match:title ^(Font Asset Creator)$
windowrule = min_size 500 250, match:class ^(Unity)$, match:title ^(Background Tasks)$
windowrule = min_size 150 300, match:initial_title (UnityEditor.PopupWindow)
windowrule = min_size 230 200, match:initial_title (UnityEditor.AddComponent.AddComponentWindow)
windowrule = min_size 500 500, match:initial_title (UnityEngine.InputSystem.Editor.AdvancedDropdownWindow)
windowrule = min_size 230 500, match:initial_title (UnityEditor.AnnotationWindow)
windowrule = min_size 300 200, match:initial_title (UnityEditor.IMGUI.Controls.AdvancedDropdownWindow)
windowrule = move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(UnityEditor.IMGUI.Controls.AdvancedDropdownWindow)$
windowrule = move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(UnityEngine.InputSystem.Editor.AdvancedDropdownWindow)$
windowrule = move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(UnityEditor.PopupWindow)$
# windowrulev2 = move cursor, class:^(Unity)$
# Color Picker for unity
windowrule = move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(Color)$
windowrule = move cursor_x cursor_y, match:class ^(Unity)$, match:title ^(HDR Color)$
# Fix dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
# Prevent Waybar tooltips and menus from triggering animations (somewhat)
layerrule {
    name = waybar-flicker-fix
    match:namespace = waybar
    match:namespace = tooltip
    no_anim = true
    blur = true
    ignore_alpha = 0.5
}